### PR TITLE
Added USPS Holidays

### PR DESCRIPTION
**Pull request by elipoultorak**
The USPS holidays are based on Part 608, section 3.2 of the DMM (U.S. Domestic Mail Manual). Please check that the file structure is ok.

### CODE REVIEW

**Comment by jurajmajer** [comment]
Thanks for preparing USPS holiday list. However there are problems merging USPS holidays.
Problem 1:  There are only US states under holiday_library/holiday_defs/public_holiday/usa/ and USPS is not a US state.
Problem 2: There is a check against all supported countries and their regions in HolidayCalendar.php. List of all supported US regions (=states) has to be changed in HolidayCalendar.php to introduce USPS holidays.

**Comment by elipoultorak** [comment]
So where do you suggest putting that file?

**Comment by jurajmajer** [comment]
I consider introducing new holiday type 'postal_holiday'. There are already holiday types like public_holiday, school_holiday etc. I'll implement it in a couple of days and use your excellent document for USPS.

**Comment by jurajmajer** [comment]
I have committed new holiday type 'postal_holiday' including your USPS document.

**Pull request closed without merging**
